### ISSUE TITLE
Exporting images/annotations

### ISSUE THREAD

**Issue by tobi1modna** [florianblume/6d-pat#124]
Hi Florian,
is there a way to export the annotations about the pose of the model over the 2D image and to save images with the "blue overlapped model" on them?
If not, do you think this feature would be easily extendable by myself?

**Comment by florianblume** [comment]
Hey @tobi1modna, this is currently not implemented but it should be fairly easy to achieve. Do you want to highlighted (i.e. selected) models to be saved or simply the renderings on top of the 2D image? You probably need to append a `QRenderCapture` to the Poses framegraph branch in the PoseViewer3DWidget and then add the functionality to trigger the capturing process. If you have questions you can post them here or when it becomes too difficult I'll give it a shot when I've got time.

**Comment by florianblume** [comment]
I added some basic screenshot functionality in [this branch](https://github.com/florianblume/6d-pat/tree/snapshot). It saves a screenshot when you click an object (which highlights it and also saves the highlight color, so a button to press would be better). But I hope you get the idea of how to implement it. Ignore the scripts folder, I just added it because I've been wanting to add it since forever to not always having to download the T-Less conversion scripts. At some point I want to implement a Python bridge so that you can easily define a data loading script yourself.

**Comment by florianblume** [comment]
I implemented some basic snapshot functionality which stores a snapshot in the folder you choose with the name snapshot_{imagefilename}. It's merged onto master.
