### ISSUE TITLE
save pose data problem

### ISSUE THREAD

**Issue by henrycddj** [florianblume/6d-pat#152]
hello, florianblume. Thank you for your amazing job.  
I try to save new poses data with the newest v2.4.3 for gt.yml, but the yml data cannt update(v2.4.0-2 same). May you know whats the problem?
I use tless.py to load data.  Thank you

**Comment by florianblume** [comment]
Hi,

thanks for your positive feedback :) I can reproduce the problem on my computer. The rotation of the poses seem to be wrong, too. Is it wrong for you, too? I don't have time to look into it right now but I'll try to solve it as soon as possible.

If you need to get working with the program right now the easiest solution might be to convert the `yml` files to the `json` format the program expects. There are some scripts in the [scripts folder](https://github.com/florianblume/6d-pat/tree/master/src/scripts) which allow you to adjust the T-Less data. I'm appending the converted files here for the first test folder of the dataset so that you can try it out directly. Make sure that `info.json` is IN the folder of the images. [This](http://ptak.felk.cvut.cz/darwin/t-less/v2/t-less_v2_test_canon_01.zip) is the corresponding test scene.

[tless.zip](https://github.com/florianblume/6d-pat/files/7609154/tless.zip)

**Comment by florianblume** [comment]
I'm closing this issue now due to lack of activity. I'll implement tests hopefully in the near future to prevent such issues.
