### ISSUE TITLE
Recovery orientation (and scale) post correspondence is off 

### ISSUE THREAD

**Issue by monajalal** [florianblume/6d-pat#169]
I downloaded a few images from web and used same camera intrinsics as yours for json file.

I did 6 points annotation for correspondence and after pose recovery, the mesh is overlaid onto 2D RGB image very weirdly.

Please let me know if you may have any suggestions.

I understand I am using a wrong camera pose (same as yours) for all images but I don't think it should affect it to this degree??

![Screenshot from 2024-04-22 15-12-05](https://github.com/florianblume/6d-pat/assets/1892917/934c8201-76e1-48fd-9e36-52b8c4301dbc)

![Screenshot from 2024-04-22 15-13-04](https://github.com/florianblume/6d-pat/assets/1892917/cad06e0e-7a86-4330-bf0c-b79e42aa153a)

I have the following for `info.json`

```
{
    "rubberduck.jpg": {
        "K": [3630.26229559, 0.0, 1324.14577835, 0.0, 3627.6973661, 659.22160257, 0.0, 0.0, 1.0],
        "nearPlane": 1.0
    },

    "rd1.png": {
        "K": [3630.26229559, 0.0, 1324.14577835, 0.0, 3627.6973661, 659.22160257, 0.0, 0.0, 1.0],
        "nearPlane": 1.0
    },

    "rd2.png": {
        "K": [3630.26229559, 0.0, 1324.14577835, 0.0, 3627.6973661, 659.22160257, 0.0, 0.0, 1.0],
        "nearPlane": 1.0
    },

    "rd3.png": {
        "K": [3630.26229559, 0.0, 1324.14577835, 0.0, 3627.6973661, 659.22160257, 0.0, 0.0, 1.0],
        "nearPlane": 1.0
    },


    "rd4.png": {
        "K": [3630.26229559, 0.0, 1324.14577835, 0.0, 3627.6973661, 659.22160257, 0.0, 0.0, 1.0],
        "nearPlane": 1.0
    },


    "rd5.png": {
        "K": [3630.26229559, 0.0, 1324.14577835, 0.0, 3627.6973661, 659.22160257, 0.0, 0.0, 1.0],
        "nearPlane": 1.0
    },

    "rd6.png": {
        "K": [3630.26229559, 0.0, 1324.14577835, 0.0, 3627.6973661, 659.22160257, 0.0, 0.0, 1.0],
        "nearPlane": 1.0
    }



}
```

**Comment by florianblume** [comment]
Two thoughs about this:

1. Using the right camera parameters is very important. This could explain the offset to some extent. If I remember correctly, you can use the image dimensions as fx and fy and half of these for cx and cy as good approximations.
2. You set corresponding points on one side of the object primarily. This reduces the accuracy in the rotation because there is a lot of freedom on one axis. Try to rotate the duck (by clicking on the grey circle/sphere of the gizmo, as explained in my other answer) and annotate the other wing, too. This should improve the rotation.

**Comment by monajalal** [comment]
I was able to fix it thanks a lot

![image](https://github.com/florianblume/6d-pat/assets/1892917/bd9acc01-d836-4bc3-8289-2ef61c6668e5)


![Screenshot from 2024-04-23 15-38-13](https://github.com/florianblume/6d-pat/assets/1892917/231c7272-378f-4f56-875d-5084d341e2af)
